name: Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_docker_image:
    name: Test building Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test build Docker image
        run: docker build . --file Dockerfile

  push_docker_image:
    name: Build & Publish Docker image
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --file Dockerfile -t latest -t jb3/microsoft-python-discord-bot/bot:${{ github.sha }}

      - name: Publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: jb3/microsoft-python-discord-bot/bot:${{ github.sha }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com

  deploy_to_kubernetes:
    runs-on: ubuntu-latest
    needs: [push_docker_image]
    
    steps:
      - uses: actions/checkout@v2

      - uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          
      - uses: Azure/k8s-deploy@v1
        with:
          namespace: 'default'
          manifests: |
            deployment.yaml
          images: 'docker.pkg.github.com/jb3/microsoft-python-discord-bot/bot:${{ github.sha }}'
          imagepullsecrets: |
            githubpackage
          kubectl-version: 'latest'
